name: nopCommerce CI/CD 

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      COMPOSE_PROJECT_NAME: nopcommerce
      DB_CONTAINER: nopcommerce_mssql_server
      DB_NAME: nopcommerce2
      DB_PASSWORD: yourStrong()Password

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stop Existing Containers
        run: |
          echo "🛑 Stopping and removing existing containers..."
          docker-compose down || true
          docker rm -f nopcommerce_mssql_server || true
          docker rm -f nopcommerce_web || true

      - name: Start All Containers
        run: |
          echo "🚀 Starting containers..."
          docker-compose up -d
          echo "⏱️ Waiting for services to be ready..."
          sleep 30

      - name: Smoke Tests
        run: |
          echo "🔍 Running smoke tests..."
          set -e
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000)
          [ "$HTTP_CODE" = "200" ]

          curl -sSf http://localhost:9000 | grep -qi "nopCommerce"
          curl -sSf http://localhost:9000/login | grep -qi "Email"
          docker ps | grep -q nopcommerce_mssql_server
          echo "✅ Smoke tests passed!"
